### ISSUE TITLE
Add/Update Vendor: Balsamiq Wireframes

### ISSUE THREAD

**Issue by NetCaptive** [ssotax/ssotax#106]
---
base_pricing: 12
currency: USD
name: Balsamiq
notes: SSO is available on Enterprise plan, billed annually only.
pricing_scheme: per user/month
pricing_sources:
  - https://balsamiq.com/buy/
scim_pricing: 18
sso_pricing: 18
updated_at: 2024-12-05
vendor_url: https://balsamiq.com

**Comment by MMore** [comment]
Thank you @NetCaptive
