### ISSUE TITLE
Augmentt Update

### ISSUE THREAD

**Issue by robybrisson** [ssotax/ssotax#19]
Sorry, I made some mistakes and need to correct them!  We do have a free plan, but we don't support scim.

name: Augmentt
free_sso_providers:
  Microsoft
scim_pricing: n/a
scim_starting_on_plan: n/a
sources:
  https://www.augmentt.com/pricing/
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-02-23
vendor_url: www.augmentt.com
```

**Comment by MMore** [comment]
Got it, fixed!
