### ISSUE TITLE
Cloudcannon

### ISSUE THREAD

**Issue by oscni** [ssotax/ssotax#24]
---
base_pricing: 45
currency: USD
name: Cloudcannon
notes: Only enterprise plan has SSO
pricing_scheme: per user/month
pricing_sources:
  - https://cloudcannon.com/pricing/
  - Quote
updated_at: 2024-03-25
vendor_url: https://cloudcannon.com
```

**Comment by MMore** [comment]
Thank you @oscni , I fixed the yaml and added it!
