### ISSUE TITLE
Remove Vendor: Tailscale

### ISSUE THREAD

**Issue by samlinville** [ssotax/ssotax#33]
**Why should it be removed?**

Tailscale no longer restricts any SSO providers to paid plans. All listed SSO providers (plus any other OIDC-compliant IDP) are available on all plans, including our free Personal plan tier.

Source: https://tailscale.com/pricing
Announcement blog: https://tailscale.com/blog/sso-tax-cut

**Comment by MMore** [comment]
Removed, thank you!
