### ISSUE TITLE
Time to merge back to a single project? 

### ISSUE THREAD

**Issue by jean** [ssotax/ssotax#53]
Just noticed that upstream seems to be live again? 

This branch is [133 commits ahead of](https://github.com/ssotax/ssotax/compare/robchahin%3Asso-wall-of-shame%3Amain...main), [184 commits behind](https://github.com/ssotax/ssotax/compare/main...robchahin%3Asso-wall-of-shame%3Amain) robchahin/sso-wall-of-shame:main.

**Comment by MMore** [comment]
Indeed that was the idea when I saw activity again. I tried [multiple times](https://github.com/robchahin/sso-wall-of-shame/issues/463#issuecomment-2004417566) to reach out to @robchahin @techdarko but without any success. Also I noticed the activity is very punctual but not continuously. Still there is a big backlog, crucial issues are not addressed etc...

So I just continue building a better ssotax. 🤷
