### ISSUE TITLE
Update Vendor: Vimeo

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#70]
I have no knowledge of this companies pricing, but it looks like the pricing might be incorrect. 

The notes says $10k annually, but the pricing section is based on it being $10k/month. 
The $20/month is correct for the "base level" pricing. 

At the very least, I think it should be updated to be $833.33/month to correct the whacky percentages. 

Feel free to close, just wanted to point it out.

**Comment by MMore** [comment]
Thank you so much for point that out, just fixed it! 🙏
