### ISSUE TITLE
Quadrant Information Security

### ISSUE THREAD

**Issue by beave** [ssotax/ssotax#79]
name:  Quadrant Information Security
free_sso_providers:
scim_pricing: 
scim_starting_on_plan: 
sources:
  - Quote
sso_on_free_plans: false
sso_on_all_paid_plans: true
updated_at: 2024-09-24
vendor_url: https://quadrantsec.com
```

**Comment by MMore** [comment]
Hey @beave . Unfortunately your yaml is not readable. Furthermore it looks more like a Service Provider, less than an actual SaaS tool. We only list actual SaaS tools!
