### ISSUE TITLE
Kanbanize, by the FAQs, should not be on the list

### ISSUE THREAD

**Issue by haydenwalker980** [ssotax/ssotax#90]
This may be generally disputed, or there may be another reason why they're on the list.

Per the "but it costs money to offer SSO" field in the FAQs, which says:  
> If your SSO support is a 10% price hike, you're not on this list,  

Kanbanize shouldn't be on this list - their SSO offering is calculated as a 10% price hike. As I said earlier, there may be another reason as to why they're on the bad list. They also provide SSO in the base offering (granted, it's as an addon)

**Comment by MMore** [comment]
Oh good point @haydenwalker980 . As they're two years old and seem to changed a lot (even a new name), we can easily remove them. The current pricing is not live anyway.
